export default {

  SET_READY: 'SET_READY',
  SET_CONNECTED: 'SET_CONNECTED',

  SET_PROGRESS: 'SET_PROGRESS',
  SET_ASSETS: 'SET_ASSETS',

  SET_WINDOW_SIZE: 'SET_WINDOW_SIZE',
  SET_WIDTH: 'SET_WIDTH',
  SET_HEIGHT: 'SET_HEIGHT',
};
